# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle test for pull request

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Create auth.key.properties file
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
        run: source auth-key-properties-creator.sh && echo "$AUTH_KEY" > src/main/resources/auth/auth.key.local.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        id: build-with-gradle
        run: ./gradlew prTest
        continue-on-error: true
      - name: Show info When Build Failed
        if: steps.build-with-gradle.outcome == 'failure'
        run: ./gradlew prTest -i
