name: Heroku test server deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sc0up"
          heroku_email: "Dae-Hwa_Jeong@outlook.com"
        env:
          HD_JASYPT_ENCRYPTOR_PASSWORD: ${{secrets.JASYPT_ENCRYPTOR_PASSWORD}}
          HD_JWT_SECRET_MAC: ${{secrets.JWT_SECRET_MAC}}
