name: Heroku test server deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create auth.key.properties file
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
        run: echo "$AUTH_KEY" > src/main/resources/auth.key.properties
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sc0up"
          heroku_email: "Dae-Hwa_Jeong@outlook.com"
